# Generated by Django 6.0.7 on 2026-07-07 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EvolutionChain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chain_data", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Cadena Evolutiva",
                "verbose_name_plural": "Cadenas Evolutivas",
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("generation_number", models.PositiveIntegerField(unique=True)),
            ],
            options={
                "verbose_name": "Región",
                "verbose_name_plural": "Regiones",
                "ordering": ["generation_number"],
            },
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "color",
                    models.CharField(
                        help_text="Hex color for badge (e.g. #FF0000)", max_length=7
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo",
                "verbose_name_plural": "Tipos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pokedex_number",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Número Pokédex"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image_url", models.URLField(blank=True, max_length=500)),
                (
                    "height",
                    models.PositiveIntegerField(
                        default=0, help_text="Height in decimeters"
                    ),
                ),
                (
                    "weight",
                    models.PositiveIntegerField(
                        default=0, help_text="Weight in hectograms"
                    ),
                ),
                (
                    "evolution_chain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pokemon",
                        to="pokedex.evolutionchain",
                    ),
                ),
                (
                    "evolves_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evolutions",
                        to="pokedex.pokemon",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pokemon",
                        to="pokedex.region",
                    ),
                ),
                (
                    "types",
                    models.ManyToManyField(related_name="pokemon", to="pokedex.type"),
                ),
            ],
            options={
                "verbose_name": "Pokémon",
                "verbose_name_plural": "Pokémon",
                "ordering": ["pokedex_number"],
            },
        ),
    ]
