# Generated by Django 6.0.7 on 2026-07-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokedex", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evolutionchain",
            name="api_id",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="image_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
